name: Reusable workflow example

on:
  workflow_call:
    inputs:
      test-input:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "This is running from the resuable workflow"
        echo "This was triggered from ${{ inputs.test-input }}"
