name: .NET 8 Build

on:
  workflow_call:
    inputs:
      test-input:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:

    - name: Echo Repo
      run: echo "Initialised from ${{ inputs.test-input }}"
      
    - name: Checkout code
      uses: actions/checkout@v4.1.7  

    # - name: Super-linter
    #   uses: super-linter/super-linter@v6.6.0 
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish artifact
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: dotnet-app
        path: ${{ github.workspace }}/publish
