name: .NET 8 Deploy

on:
  workflow_call:
    inputs: 
      env: 
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ input.env }}
    steps:
    - name: Checkout code
      uses: actions/setup-dotnet@v4.0.0

    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: dotnet-app
        path: ${{ github.workspace }}/publish

    - name: LS
      run: ls -a

    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: <your-app-name>
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ${{ github.workspace }}/publish
